language: node_js
node_js: 10
cache:
  yarn: true
  directories:
    - node_modules

os: linux
dist: bionic

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - yarn

script:
  - yarn deploy-storybook --ci
