// Generated by i18nline and preact-i18nline.
import I18n from 'preact-i18nline/i18n';

I18n.supportedLocales = ['en', 'pt_BR'];
I18n.defaultLocale = 'en';

I18n.import = (locale) => {
	// we use a switch here so the import statements are statically
	// analyzable. the use of import() will make build tools generate
	// separate bundles which are downloaded on-demand.
	switch (locale) {
		case 'en': return import(/* webpackChunkName: 'i18n.en' */ './en.json');
		case 'pt_BR': return import(/* webpackChunkName: 'i18n.pt_BR' */ './pt_BR.json');
		default: return import(/* webpackChunkName: 'i18n.default' */ './default.json');
	}
};

if ((typeof module === 'object') && module.hot) {
	module.hot.accept('./en.json', I18n.reload('en'));
	module.hot.accept('./pt_BR.json', I18n.reload('pt_BR'));
	module.hot.accept('./default.json', I18n.reload('default'));
}

export default I18n;
