version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./package.json
            - ./build
            - ./CHANGELOG.md
            - ./build.tar.gz
  loki:
    docker:
      - image: chinello/alpine-chrome:with-node
    working_directory: ~/repo
    environment:
      CHROME_PATH: /usr/bin/chromium-browser
    steps:
      - checkout
      - run: yarn
      - run: yarn run build-storybook:loki
      - run: |
          cat package.json | sed s/\.docker/.app/ > package.json-new
          mv package.json-new package.json
      - run: yarn run loki:test-ci
      - store_artifacts:
          path: ~/repo/.loki/difference
  publish:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
      - run:
          name: Github Release
          command: yarn release -y

  storybook:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run:
          name: Storybook
          command: yarn deploy-storybook --ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - loki:
          requires:
            - build
      - publish:
          requires:
            - loki
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - storybook:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
